### ISSUE TITLE
qiitaでガイドラインを違反したので新しいblog場所候補

### ISSUE THREAD

**Issue by superTonguman** [RikiishiSuzunosuke/AIspeaker_yosie#14]

**Comment by superTonguman** [comment]
候補
1.はてなブログ
2.note
3.ライブドアブログ

**Comment by RikiishiSuzunosuke** [comment]
共同執筆できるサイトがいいね

**Comment by superTonguman** [comment]
そこを考慮して調べてみる

**Comment by superTonguman** [comment]
1.はてなブログ
メリット
　　すぐに書けれる　共同執筆可能
デメリット
　　デザイン・カスタマイズに制限がある　
2.note
メリット
  　アカウントを取得すれば無料ですぐに使える
デメリット
　　デザインのカスタマイズができない

3.ライブドアブログ
メリット
　　スマートフォン対応シンプルなデザイン直感的に使える
　　共同執筆可能
デメリット
　　作成者以外オーナーにはなれない
この中だとライブドアブログに票を入れたい

**Comment by RikiishiSuzunosuke** [comment]
個人的にはそんなにデザイン性は重視してない。
最低限共同執筆できればいいと思ってるから、山田がライブドアを推すならそれでいいかな。
スマホでも書きやすいなら有り難いし。

**Comment by superTonguman** [comment]
じゃあそうします

**Comment by superTonguman** [comment]
このイシュー閉じていい？

**Comment by RikiishiSuzunosuke** [comment]
了解。調べてくれてありがとう。
結論が出たらクローズしちゃっていいよ。
