### ISSUE TITLE
ライブブドアブログを使う準備

### ISSUE THREAD

**Issue by RikiishiSuzunosuke** [RikiishiSuzunosuke/AIspeaker_yosie#16]
アカウントを作成しましょう

**Comment by RikiishiSuzunosuke** [comment]
カンバンとマイルストーン連携してみたけど、果たしてあっているのかどうか

**Comment by superTonguman** [comment]
いい感じにできてるよ
メンバーに招待したいのでIDください

**Comment by superTonguman** [comment]
ライブドアアカウントの

**Comment by RikiishiSuzunosuke** [comment]
ありがとう
ID→yosie_mother

**Comment by superTonguman** [comment]
見つからないって出てきちゃう

**Comment by RikiishiSuzunosuke** [comment]
マジ？
メルアドとかでは招待できない？

**Comment by superTonguman** [comment]
メルアドだと形式が違うらしい

**Comment by RikiishiSuzunosuke** [comment]
![スクリーンショット 2021-07-28 211914](https://user-images.githubusercontent.com/84367202/127321134-e31f5886-043a-49e9-a1b0-45795c9aca1e.png)

**Comment by RikiishiSuzunosuke** [comment]
これスクショなんだけど、もう一回試してみて

**Comment by superTonguman** [comment]
だめだできない

**Comment by RikiishiSuzunosuke** [comment]
招待するところのスクショって送ってもらえたりする？？

**Comment by superTonguman** [comment]
一応 ID: pandakingdam

**Comment by RikiishiSuzunosuke** [comment]
招待画面みたいなの送れる？

**Comment by superTonguman** [comment]
![スクリーンショット 2021-07-28 212621](https://user-images.githubusercontent.com/84367300/127321962-0c934c3b-c646-4b00-b079-6a46a0a3df15.png)

**Comment by RikiishiSuzunosuke** [comment]
一回メルアドで招待してみてくれる？

**Comment by RikiishiSuzunosuke** [comment]
200221bt@yse-c.net

**Comment by superTonguman** [comment]
完了しました。って出た

**Comment by RikiishiSuzunosuke** [comment]
招待メールが届いて無事参加、閲覧できました

**Comment by superTonguman** [comment]
やりましたわ

**Comment by RikiishiSuzunosuke** [comment]
明日のブログは私が書きますわ
とりあえずブログのタイトルを”pandakingdamのブログ”から変更してくださいまし。

**Comment by superTonguman** [comment]
YoSiE familyのblogに変えておきましたわ

**Comment by RikiishiSuzunosuke** [comment]
ありがとうございます。
それから、今後投稿する記事のタイトルには末尾に”＃3”などと、ナンバリングするようにしてはいかがかしら。
