### ISSUE TITLE
データ取得に関する改良案

### ISSUE THREAD

**Issue by RikiishiSuzunosuke** [RikiishiSuzunosuke/AIspeaker_yosie#160]
占い・天気はいちいち取得していると時間がかかるため、バッチ処理で定期的に取得する
そうすれば、占い・天気の出力の時間が削減できる

**Comment by RikiishiSuzunosuke** [comment]
起動時に処理でもいいかもしれない。起動にさらに時間がかかるけど。

**Comment by RikiishiSuzunosuke** [comment]
この処理に時間がかかるのであれば、sleepは削除できるから＋ー若干マイナス暗いかな

**Comment by superTonguman** [comment]
かかっても良い影響があるならばよいと思う

**Comment by RikiishiSuzunosuke** [comment]
yosie.shの冒頭に追記かな

**Comment by superTonguman** [comment]
それでいこう

**Comment by RikiishiSuzunosuke** [comment]
uranai.txtとtenki.txtに書き込んで、ラベル判断の時にif分けして呼び出しファイルを替えよう

**Comment by RikiishiSuzunosuke** [comment]
ニュースも八種類txtファイル作って、先に書きこんでおいて、ランダムで渡してもいいかもね

**Comment by superTonguman** [comment]
それはバリエーションが増えて面白そう

**Comment by RikiishiSuzunosuke** [comment]
バリエーションは元の出力内容と変わらんよ
