### ISSUE TITLE
現在発生している問題

### ISSUE THREAD

**Issue by RikiishiSuzunosuke** [RikiishiSuzunosuke/AIspeaker_yosie#161]
ラズパイでmodel.binを呼び出して予測するためにfastTextをインストールしたが、
+ fastTextがimportできない
+ load_modelメソッドが呼び出せない
の2パターンのエラーに直面

**Comment by superTonguman** [comment]
[Python: gensim で学習済み単語ベクトル表現を扱ってみる](https://blog.amedama.jp/entry/gensim-fasttext-pre-trained-word-vectors)

**Comment by superTonguman** [comment]
[Fasttext for Python - module 'fasttext' has no attribute 'load_model'](https://pretagteam.com/question/fasttext-for-python-module-fasttext-has-no-attribute-loadmodel)

**Comment by RikiishiSuzunosuke** [comment]
[関連Issues](https://github.com/facebookresearch/fastText/issues/1131)

**Comment by RikiishiSuzunosuke** [comment]
sudo apt install libatlas-base-dev
export LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1.2.0

**Comment by RikiishiSuzunosuke** [comment]
[動いたらしい](https://github.com/explosion/spaCy/issues/6638)

**Comment by RikiishiSuzunosuke** [comment]
FastText.pyのファイル名をfast_text.pyに変更して、
fast_text.pyとtest_model.pyを同じディレクトリに入れて実行したら動いた！
