### ISSUE TITLE
YoSiEに必要な技術について

### ISSUE THREAD

**Issue by RikiishiSuzunosuke** [RikiishiSuzunosuke/AIspeaker_yosie#18]
YoSiE作成に当たって必要になる技術を検討しましょう。
例：OpenJTalk, tensorflow など

**Comment by RikiishiSuzunosuke** [comment]
技術が必要な個所
・音声認識(自作, Julius?)
・ウェイクワード(ライブラリ?)
・機械学習(tensorflow? テキスト分類)
・サイトからテキストを持ってくる(スクレイピング, html)
・読み上げ(gTTS, OpenJTalk?)

**Comment by superTonguman** [comment]
scrapboxのリンク集に記事を載せました。

**Comment by superTonguman** [comment]
音声をテキストにするという記事を見つけました[https://self-development.info/pythonで音声からテキストへ変換【speechrecognition】/](url)

**Comment by RikiishiSuzunosuke** [comment]
リンクの修正をお願いします

**Comment by superTonguman** [comment]
https://self-development.info/python%E3%81%A7%E9%9F%B3%E5%A3%B0%E3%81%8B%E3%82%89%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%E3%81%B8%E5%A4%89%E6%8F%9B%E3%80%90speechrecognition%E3%80%91/
直してみました

**Comment by superTonguman** [comment]
リンクが長くなった

**Comment by RikiishiSuzunosuke** [comment]
[テキスト](url)
で書き込みをお願いします

**Comment by RikiishiSuzunosuke** [comment]
[参考サイト](https://self-development.info/python%E3%81%A7%E9%9F%B3%E5%A3%B0%E3%81%8B%E3%82%89%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%E3%81%B8%E5%A4%89%E6%8F%9B%E3%80%90speechrecognition%E3%80%91/)

**Comment by superTonguman** [comment]
[音声をテキストにするという記事を見つけました](https://self-development.info/python%E3%81%A7%E9%9F%B3%E5%A3%B0%E3%81%8B%E3%82%89%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%E3%81%B8%E5%A4%89%E6%8F%9B%E3%80%90speechrecognition%E3%80%91/)

**Comment by RikiishiSuzunosuke** [comment]
[rspiをOpenJTalkで喋らせる](https://jellyware.jp/kurage/raspi/raspi_speech_synthesis.html)

**Comment by RikiishiSuzunosuke** [comment]
[日本語をテキスト分類](https://qiita.com/kenta1984/items/4452e91db806ee765a78)

**Comment by RikiishiSuzunosuke** [comment]
[BERTで日本語テキストの感情分析(クラス分類)[https://qiita.com/namakemono/items/4c779c9898028fc36ff3]
