### ISSUE TITLE
インセプションデッキ作成

### ISSUE THREAD

**Issue by RikiishiSuzunosuke** [RikiishiSuzunosuke/AIspeaker_yosie#22]
インセプションデッキを作成しましょう
いらない項目などは相談しましょう

**Comment by RikiishiSuzunosuke** [comment]
## インセプションデッキに記載する項目(必須)
・プロジェクト名(決定済み)
・プロジェクト名の由来(決定済み)
・我々はなぜここにいるのか、プロジェクトの根幹に関わる理由
・エレベーターピッチ
・技術的な解決策の概要
・期間を見極める

**Comment by RikiishiSuzunosuke** [comment]
ひとまず、以上の項目のみのインセプションデッキ用のファイルを新規作成します。

**Comment by RikiishiSuzunosuke** [comment]
げ、ごめん間違えてmainのままやっちゃった

**Comment by superTonguman** [comment]
あらら

**Comment by RikiishiSuzunosuke** [comment]
以後気を付けます
書く項目の割り振りどうしようか。
とりあえず必須項目だけ

**Comment by RikiishiSuzunosuke** [comment]
あ、追記
mvでファイル名変更しようとしたらファイル増えたわ

**Comment by superTonguman** [comment]
とりあえずclone しました。

**Comment by RikiishiSuzunosuke** [comment]
pullじゃなくて？

**Comment by superTonguman** [comment]
pull?

**Comment by RikiishiSuzunosuke** [comment]
え？？　最新のリポジトリにするのはpullだよ？

**Comment by superTonguman** [comment]
こっちでまだcloneしてなかった

**Comment by RikiishiSuzunosuke** [comment]
あぁ……そういうことね

**Comment by RikiishiSuzunosuke** [comment]
cloneして、markdown-inception-deck.mdがあったら教えて

**Comment by superTonguman** [comment]
down-inception-deck.mdあったよ

**Comment by superTonguman** [comment]
markdown-inception-deck.mdあります。

**Comment by RikiishiSuzunosuke** [comment]
まじか
じゃあそれブランチ作って、rmで削除してpushしてくれ
多分それでcodeの欄から消える

**Comment by superTonguman** [comment]
了解

**Comment by RikiishiSuzunosuke** [comment]
あ、多分rmしたときはaddしないでcommitしちゃっていいと思う

**Comment by superTonguman** [comment]
トークン要求されたんだけど何返せばいいのかわかんね

**Comment by RikiishiSuzunosuke** [comment]
トークン作ってないの？
授業で説明してたやつだよ

**Comment by superTonguman** [comment]
作ったけどあれ結局なに？

**Comment by RikiishiSuzunosuke** [comment]
今後パスワードの代わりになるやつだって説明してたでしょうが
それを入力するの

**Comment by superTonguman** [comment]
作り直すわ

**Comment by RikiishiSuzunosuke** [comment]
どこかに保存しなかったの？？
まぁ作り直してもいいけどさ

**Comment by superTonguman** [comment]
保存したけど学校のファイルだったわ

**Comment by RikiishiSuzunosuke** [comment]
あほたれぇ！！！！！

**Comment by RikiishiSuzunosuke** [comment]
まぁトークン作ってpushしてくれ
そしたら割り振り決めよう

**Comment by RikiishiSuzunosuke** [comment]
なんかおかしくない？
コミット数えらいことになってるけど

**Comment by superTonguman** [comment]
なんかもうよくわかんない

**Comment by RikiishiSuzunosuke** [comment]
いいや、取り合えずプルリク頼むわ

**Comment by superTonguman** [comment]
rmしたけどpullリクエストできん

**Comment by RikiishiSuzunosuke** [comment]
じゃあプルリクエストのとこ開いてブランチ選んでプルリクして

**Comment by superTonguman** [comment]
やっぱできん

**Comment by RikiishiSuzunosuke** [comment]
いいわ、こっちでcloneしなおしてみる

**Comment by superTonguman** [comment]
お願いします

**Comment by RikiishiSuzunosuke** [comment]
ブランチだと削除ができないみたいだからメインで削除します

**Comment by RikiishiSuzunosuke** [comment]
pullしたらmarkdown~消えた……謎すぎる

**Comment by superTonguman** [comment]
ん？？？？？？

**Comment by RikiishiSuzunosuke** [comment]
だめだ、わからんから放置しとこ……休み明けに先生に見てもらお。

**Comment by superTonguman** [comment]
そうだな

**Comment by RikiishiSuzunosuke** [comment]
取り合えずインセプションデッキの割り振りしよう、必須項目の。
書き込むのは .testじゃないほうね。必須項目だけ気に抜いたやつあるから、そっち。

**Comment by RikiishiSuzunosuke** [comment]
・我々はなぜここにいるのか、プロジェクトの根幹に関わる理由
・エレベーターピッチ
・技術的な解決策の概要
・期間を見極める

書くのはこれね

**Comment by superTonguman** [comment]
うーんどれ書こうか

**Comment by RikiishiSuzunosuke** [comment]
めんどくさそうな上二つ引き受けようか

**Comment by superTonguman** [comment]
期間の見極めとはどういう感じで書けばいいのか

**Comment by RikiishiSuzunosuke** [comment]
うーん、取り合えず仮定だから気楽に考えてはいいと思うんだけど……
取り合えずスプリント区切りでって感じかな

**Comment by superTonguman** [comment]
わかった書いてみるよ

**Comment by RikiishiSuzunosuke** [comment]
一応pushする前に、書いた内容issueに挙げてもらっていい？
書き直すとこお互いに見つけよ

**Comment by superTonguman** [comment]
オッケー

**Comment by RikiishiSuzunosuke** [comment]
プロジェクトの根幹に関わる理由

これまで経験のなかったハードウェアを扱ってみたかったから。
また、スマートスピーカーを自ら作ることで、ブラックボックス状態だったスマートスピーカー中身を深く知ることができると考えたから。

**Comment by superTonguman** [comment]
いいと思うよ

**Comment by RikiishiSuzunosuke** [comment]
了解
エレベーターピッチむず

**Comment by RikiishiSuzunosuke** [comment]
## ・エレベーターピッチ　※

- 日常生活の些細な手助けがほしい
- 小学生以上向けの
- 'AIスピーカーYoSiE'というプロダクトは、
- スマートスピーカー です。
- これは、話し掛けることで天気や日時の確認ができます。
- AlexaやGoogleHomeの簡易版です。機能が既製品に比べてシンプルなため、気軽に利用することができます。

こんな感じかねぇ
いろいろ書き替えてるけど

**Comment by superTonguman** [comment]
小学生以上向けので止まってるけど

**Comment by superTonguman** [comment]
難しそうだな

**Comment by RikiishiSuzunosuke** [comment]
あれ？こっちだと全文見えるんだけどな
もっかい貼るわ

**Comment by RikiishiSuzunosuke** [comment]
## ・エレベーターピッチ　※

- 日常生活の些細な手助けがほしい
- 小学生以上向けの
- 'AIスピーカーYoSiE'というプロダクトは、
- スマートスピーカー です。
- これは、話し掛けることで天気や日時の確認ができます。
- AlexaやGoogleHomeの簡易版です。機能が既製品に比べてシンプルなため、気軽に利用することができます。

**Comment by superTonguman** [comment]
全部見えたいいと思うよ
こっちも一応sprint04まで書けた

- sprint_01
	スマートスピーカーやラズパイについて調べる

- sprint_02
	音声認識やスマートスピーカーっで何ができるか調べる

- sprint_03
	ラズパイの初期設定を完了させる

- sprint_04
	ラズパイにOpenJTalkをインストールししゃべらせる

**Comment by RikiishiSuzunosuke** [comment]
あーーそこまで細かくなくていいんじゃない？
pptの見本も構築、テスト、トレーニングの三分割くらいだし

**Comment by RikiishiSuzunosuke** [comment]
でも難しいよなぁ

**Comment by RikiishiSuzunosuke** [comment]
スプリント区切りっつった俺の言い方が悪かったな

**Comment by superTonguman** [comment]
うん難しい
これを考えずに書けるようにしたい

**Comment by RikiishiSuzunosuke** [comment]
いや誰でも考えないでは書けないよ。楽に書けるようになりたい、でしょ。

**Comment by superTonguman** [comment]
それが言いたかった

**Comment by RikiishiSuzunosuke** [comment]
3~9スプリント　開発
10スプリント　テスト
…
見たいな感じかなぁ

**Comment by superTonguman** [comment]
なるほど書き直してみる

**Comment by RikiishiSuzunosuke** [comment]
うん
取り合えずこっちの二項目はpushとプルリクしちゃうわ

**Comment by superTonguman** [comment]
ok

**Comment by superTonguman** [comment]
##書き直してみた

- 1～2スプリント
	探索

- 3～7スプリント
	開発に向けて準備　プレゼンあり

- 8～13スプリント
	開発　

- 14スプリント
	テストとプレゼン

**Comment by RikiishiSuzunosuke** [comment]
うん、取り合えずそんな感じでいいと思う
後は先生に修正箇所言われたら直そう

**Comment by superTonguman** [comment]
オッケーpushするわ

**Comment by RikiishiSuzunosuke** [comment]
おｋ

**Comment by RikiishiSuzunosuke** [comment]
じゃああとは利用する技術お願いね。
わかんないのあればissueで言って。

**Comment by superTonguman** [comment]
オッケー

**Comment by superTonguman** [comment]
##　・書いてみました

- [Python]
- [Raspberry Pi]
- [OpenJTalk]
- [スクレイピング]
- [※ Julius]

**Comment by RikiishiSuzunosuke** [comment]
スクレイピングのところ、
BeautifulSoup4
に書き換えておいて

**Comment by RikiishiSuzunosuke** [comment]
beautifulsoup4はライブラリ名ね

**Comment by superTonguman** [comment]
おｋ

**Comment by superTonguman** [comment]
書き直した
- [Python]
- [Raspberry Pi]
- [OpenJTalk]
- [beautifulsoup4]
- [※ Julius]

**Comment by RikiishiSuzunosuke** [comment]
そこ書き換えたらpushしていいよ
あとは決まり次第追記していこう

**Comment by superTonguman** [comment]
おｋ

**Comment by RikiishiSuzunosuke** [comment]
あ、ごめん

**Comment by RikiishiSuzunosuke** [comment]
BeautifulSoup4にして。一応ライブラリ名だから、大文字小文字の区別つけたほうがいいと思う。

**Comment by superTonguman** [comment]
いったんpullリクエスト送りる

**Comment by RikiishiSuzunosuke** [comment]
了解

**Comment by RikiishiSuzunosuke** [comment]
ok
あとはさっきのところ直してもう一回プルリクして、今日の作業は終わりかな

**Comment by RikiishiSuzunosuke** [comment]
じゃあインセプションデッキの作成はこれでひと段落です
今週の残りは各自で勉強しましょう

**Comment by RikiishiSuzunosuke** [comment]
このisuue閉じるけど平気？

**Comment by superTonguman** [comment]
平気
