### ISSUE TITLE
スクレイピングに関するissue

### ISSUE THREAD

**Issue by RikiishiSuzunosuke** [RikiishiSuzunosuke/AIspeaker_yosie#30]

**Comment by RikiishiSuzunosuke** [comment]
WindowsとRaspberry Piだとスクレイピングの勝手が違うかもしれんな

**Comment by superTonguman** [comment]
いいサイトを見つけましたリンク集に乗せたので見てください

**Comment by RikiishiSuzunosuke** [comment]
まったく同じもの見てました()

**Comment by superTonguman** [comment]
かなり大爆笑

**Comment by RikiishiSuzunosuke** [comment]
良さげなタイトル発見
内容確認してからリンク集に追加します
[こちら](https://chiroru.hatenablog.com/entry/2020/05/14/034923)

**Comment by RikiishiSuzunosuke** [comment]
ちょっっとこれは夏休みの課題になりそうですね

**Comment by superTonguman** [comment]
結構hardな内容ですな

**Comment by RikiishiSuzunosuke** [comment]
Raspberry Pi、音声認識、スクレイピングが3大課題だな

**Comment by superTonguman** [comment]
最初にどれから片付けようか

**Comment by RikiishiSuzunosuke** [comment]
ラズパイの初期操作とかできるのは再来週以降だし、音声認識は書籍が届くのが未定
となるとスクレイピングだろうけど、実行環境がラズパイなだけになんとも

**Comment by RikiishiSuzunosuke** [comment]
取り敢えずスクレイピングだけじゃなくて、ほかにも天気とかを読み上げる技術を探そう。たぶんスクレイピングがすべてではないから。

**Comment by superTonguman** [comment]
確かにスクレイピングだけに絞るのは弱いから別で探してみる

**Comment by RikiishiSuzunosuke** [comment]
それでいこう
ちなみに前リンク集に貼った天気読み上げ目覚まし時計で利用してた、livedoorのwether hacksはサ終してた

**Comment by superTonguman** [comment]
twitterのタイムラインをラズパイで読み上げる記事を見つけましたhttps://qiita.com/mizo0203/items/7704e725a774bca4c2bc Raspberry Pi

**Comment by RikiishiSuzunosuke** [comment]
面白いけどちょっと方向性が違うな

**Comment by superTonguman** [comment]
なるほど

**Comment by RikiishiSuzunosuke** [comment]
取り敢えずニュースと天気だけに絞ろうか
全体的な土台が出来てきたら機能追加もできるだろうから、リンクは取っておいて

**Comment by RikiishiSuzunosuke** [comment]
[phpプログラミングでニュース読み上げ](https://deathmarch.net/archives/191)
以前貼ったリンクだけど、使えそう

**Comment by superTonguman** [comment]
こっちも天気予報をスマートスピーカーで読み上げるサイトを見つけたけどちょっと読みにくいかも
[https://www.webzoit.net/hp/it/internet/homepage/env/iot/raspberry_pi/smart_speaker/weather/ 自作ラズパイスマートスピーカーで天気予報を読み上げ(8/3)]

**Comment by RikiishiSuzunosuke** [comment]
このサイト役立ちそうで俺もいくつかリンク貼ったけど、見にくいのが難点だよな

**Comment by superTonguman** [comment]
本当にそうなんだよね何年前のだよって感じ

**Comment by RikiishiSuzunosuke** [comment]
天気関連は一旦Done

**Comment by superTonguman** [comment]
同意

**Comment by RikiishiSuzunosuke** [comment]
プロトタイプをアップデートするので、山田は引き続き調べものお願いします

**Comment by superTonguman** [comment]
了解しました。

**Comment by RikiishiSuzunosuke** [comment]
[ニュースのスクレいピング(beautifulsoup)](https://rurukblog.com/post/python-webscraping-ynews/
