### ISSUE TITLE
rspiのインストール～初期設定

### ISSUE THREAD

**Issue by RikiishiSuzunosuke** [RikiishiSuzunosuke/AIspeaker_yosie#36]
力石のPCだと吉川さんの邪魔になるので、山田のPＣでやりましょう

**Comment by superTonguman** [comment]
椅子を用意しておきますわ

**Comment by RikiishiSuzunosuke** [comment]
必要機器は一通り先生が揃えてくださったので、[こちら](https://jellyware.jp/kurage/raspi/raspberrypi.html)の記事を参考にしながら進めましょう

**Comment by superTonguman** [comment]
わかりました

**Comment by RikiishiSuzunosuke** [comment]
error
noobsは起動したが、wi-fiの設定をしなければならず、wi-fiがつながらなかったため、インストール段階から再度やり直してみることに

**Comment by superTonguman** [comment]
再インストールしなおした後、ラズパイを起動したところ、前回とは違う挙動を見せたものの、またwi-fiの設定を求められてしまった

**Comment by RikiishiSuzunosuke** [comment]
wi-fiが現在最大の問題なので、まずは時間で解決できるか試してみる

**Comment by RikiishiSuzunosuke** [comment]
より細かく手順が書かれてるサイトを見つけました→[こちら](https://pcmanabu.com/raspberry-pi4-install/#NOOBS)
これによると、wi-fiにつながると選べるオプションが増えるらしい
ただ、これと違って現在rasbianなどの表示がこちらでは出ていない

**Comment by RikiishiSuzunosuke** [comment]
ネットワークにつながったらOSが表示された！！

**Comment by RikiishiSuzunosuke** [comment]
せめて今日中にOSのインストールだけ済ませたいね

**Comment by superTonguman** [comment]
osは合計11個表示されました。
確かに済ませたいね

**Comment by RikiishiSuzunosuke** [comment]
たぶん一番上のやつだよね、rasbian

**Comment by superTonguman** [comment]
そうね一番上のやつが推奨されてるね

**Comment by RikiishiSuzunosuke** [comment]
ok、じゃあそれだ
インストールボタン押せるようになってる？

**Comment by superTonguman** [comment]
選んで押せるようになってる

**Comment by superTonguman** [comment]
まだ押してないよ

**Comment by RikiishiSuzunosuke** [comment]
了解。じゃあ後で作業時間か休み時間になったらインストールしちゃおう。15分くらいかかるらしいから

**Comment by superTonguman** [comment]
了解

**Comment by RikiishiSuzunosuke** [comment]
インストール開始、予想所要時間15分

**Comment by superTonguman** [comment]
現在0%

**Comment by superTonguman** [comment]
インストール完了→初期設定完了→ソフトウェアアップデート中(今ここ)

**Comment by RikiishiSuzunosuke** [comment]
今日中(8/6)にアップデートが終わらなかった場合、日曜日に確認
