### ISSUE TITLE
夏休み中の作業について

### ISSUE THREAD

**Issue by RikiishiSuzunosuke** [RikiishiSuzunosuke/AIspeaker_yosie#37]
【提案】
・インセプションデッキの完成
・発話意図分類の機械学習モデルの試作
・音声認識の勉強
・RsPiにプロトタイプを移植する

**Comment by RikiishiSuzunosuke** [comment]
tensorflowのチュートリアルの[テキスト分類](https://www.tensorflow.org/tutorials/keras/text_classification?hl=ja)を再確認しましょう

**Comment by RikiishiSuzunosuke** [comment]
音声認識の書籍が届き次第、先生に連絡をしていただくので、休み中に取りに行きます

**Comment by RikiishiSuzunosuke** [comment]
インセプションデッキはissueかslack、meetなどで話し合いながら決定しましょう

**Comment by superTonguman** [comment]
わかりました
