### ISSUE TITLE
OpenJTalk設定

### ISSUE THREAD

**Issue by RikiishiSuzunosuke** [RikiishiSuzunosuke/AIspeaker_yosie#38]
仮決定
話者：Mei(Bashful)
声質：0.61
ピッチシフト：1
話速：1.2

**Comment by RikiishiSuzunosuke** [comment]
[パラメーターの参考資料](http://moblog.absgexp.net/openjtalk/#OpenJtalk)

**Comment by superTonguman** [comment]
[OpenJTalkを効率よくしゃべらせる](https://windvoice.hatenablog.jp/entry/2015/02/22/165457)

**Comment by RikiishiSuzunosuke** [comment]
決定
Mei_happy
-r 1.3
-a 0.55
